"""Prompt templates for agents."""

from .analyzer_prompts import (
    ANALYZER_SYSTEM_PROMPT,
    ANALYZER_USER_PROMPT,
    PROFILER_SYSTEM_PROMPT,
    PROFILER_USER_PROMPT,
    MEMORY_SYSTEM_PROMPT,
    MEMORY_USER_PROMPT
)
from .optimizer_prompts import (
    OPTIMIZER_SYSTEM_PROMPT,
    OPTIMIZER_USER_PROMPT
)
from .validator_prompts import (
    VALIDATOR_SYSTEM_PROMPT,
    VALIDATOR_USER_PROMPT
)

__all__ = [
    "ANALYZER_SYSTEM_PROMPT",
    "ANALYZER_USER_PROMPT",
    "PROFILER_SYSTEM_PROMPT",
    "PROFILER_USER_PROMPT",
    "MEMORY_SYSTEM_PROMPT",
    "MEMORY_USER_PROMPT",
    "OPTIMIZER_SYSTEM_PROMPT",
    "OPTIMIZER_USER_PROMPT",
    "VALIDATOR_SYSTEM_PROMPT",
    "VALIDATOR_USER_PROMPT",
]